spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    # locations: "classpath:db/migration"
  h2:
    console:
      enabled: true # habilita a console do H2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        formatSql: true

springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/v1/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:8080,http://localhost:4200

security:
  jwt:
    token:
      secret-key: Secrettest3
      expire-length: 3600000
# flyway:
#   enabled: true
#   validate-on-migrate: true

# spring.jpa.hibernate.ddl-auto = create

 