spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    # locations: "classpath:db/migration"
  h2:
    console:
      enabled: true # habilita a console do H2
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        format_sql: true

cors:
  originPatters: http://localhost:8080,http://localhost:4200
# flyway:
#   enabled: true
#   validate-on-migrate: true

# spring.jpa.hibernate.ddl-auto = create

 