CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authority VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS permission
ADD
    CONSTRAINT unique_permission_authority UNIQUE (authority);