CREATE TABLE basic_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    `password` VARCHAR(255),
    `enabled` BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS basic_token
ADD
    CONSTRAINT unique_basic_token_username UNIQUE (username);